object: orig/eu/sys/main.dol
hash: 10d34dbf901e5d6547718176303a6073ee80dda2
symbols: config/eu/symbols.txt
splits: config/eu/splits.txt

#map: orig/GAMEID/files/main.MAP
mw_comment_version: 15
quick_analysis: false
detect_objects: true
detect_strings: true
symbols_known: false
fill_gaps: true
