# See config.example.yml for documentation.
object: orig/jp/sys/main.dol
hash: a564033aee46988743d8f5e6fdc50a8c65791160
symbols: config/jp/symbols.txt
splits: config/jp/splits.txt

# TODO: why are these stripped?
force_active: [
  "@81",
  "__RTTI__Q23std9exception",
  "@260",
  __RTTI__Q23std8bad_cast,
]

mw_comment_version: 15 # Wii Linker 1.1
symbols_known: true # Very fast analysis
fill_gaps: false # Alignments known
