# See config.example.yml for documentation.
object: orig/SX4J01/sys/main.dol
hash: a564033aee46988743d8f5e6fdc50a8c65791160
symbols: config/SX4J01/symbols.txt
splits: config/SX4J01/splits.txt

force_active: []

mw_comment_version: 15 # Wii Linker 1.1
symbols_known: true # Very fast analysis
fill_gaps: true # Alignments known
